{% set name = "gitui" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/extrawurst/gitui/archive/v{{ version }}.tar.gz
  sha256: 5180d5d8fd2fe6400148d6078b4b318c7530ca6c27ea8d8c0882f2e4d9064a80

build:
  number: 0
  ignore_run_exports:
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - make
    - perl  # [win]
    - cargo-bundle-licenses
  host:
    - openssl

test:
  commands:
    - gitui --help

about:
  home: https://github.com/extrawurst/gitui
  summary: 'blazing fast terminal-ui for git'
  description:  'Blazing 💥 fast terminal-ui for git written in rust 🦀'
  license: MIT
  license_family: MIT
  license_file: 
    - THIRDPARTY.yml
    - LICENSE.md
  dev_url: https://github.com/extrawurst/gitui

extra:
  recipe-maintainers:
    - TheBlackSheep3
